### ISSUE TITLE
Move TF client from main library

### ISSUE THREAD

**Issue by FrostHand** [uml-robotics/ROS.NET#12]
TF and its heavy math dependencies should be separated from main ROS_C-Sharp library. (Creating separate issue from previous conversation)

**Comment by FrostHand** [comment]
Most of game engines (I use Unity3D, but OGRE has exactly the same concepts) has its own concepts for keeping transform trees and provide means for getting transforms between scene nodes. So the only receiving part(reading tf/tf2 messages from ROS) is necessary. 

Maybe we could implement 'core' TF client, with several 'transformer' implementations.

**Comment by gavanderhoorn** [comment]
Perhaps the [tf2 design](http://wiki.ros.org/tf2/Design) could provide some inspiration.

**Comment by nuclearmistake** [comment]
https://github.com/uml-robotics/ROS.NET/commit/a99c702a63d6d68f96a52449467a665bb7237044
