### ISSUE TITLE
'Messages.MsgTypes' does not contain a definition for 'std_msgs__short'

### ISSUE THREAD

**Issue by nickkazepis** [uml-robotics/ROS.NET#13]
I'm trying to compile a custom message that contains the line:
**std_msgs/Int16[] data**
and I get multiple errors: *'Messages.MsgTypes' does not contain a definition for 'std_msgs__short'*

Tracing the code creation I found that the type Int16 is not recognized as a ros type and the "meta" variable is being set to true. Can you please help?

**Comment by nuclearmistake** [comment]
Remove std_msgs from your custom message definition... Should just be Int16

**Comment by nickkazepis** [comment]
It was a custom message from shadow robot (http://wiki.ros.org/shadow_robot).
Thank you!

**Comment by gavanderhoorn** [comment]
Just to clarify: `Int16` is a member of the `std_msgs` package / namespace. See [wiki.ros.org/std_msgs](http://wiki.ros.org/std_msgs) and [std_msgs/Int16](http://docs.ros.org/api/std_msgs/html/msg/Int16.html).

**Comment by nuclearmistake** [comment]
Their messages have "int16"... Their messages wouldn't error.

**Comment by nickkazepis** [comment]
This is the message I tried to compile:
https://github.com/shadow-robot/sr-ros-interface/blob/indigo-devel/sr_robot_msgs/msg/Tactile.msg
It explicitly states std_msgs/Int16[] data

**Comment by nuclearmistake** [comment]
Yes... But literal types in custom messages don't need their fully qualified type names.

**Comment by gavanderhoorn** [comment]
But it is valid, according to the `rosmsg` spec.

**Comment by nuclearmistake** [comment]
Aye. I'm not debating the spec. I'm telling you how to make it compile and hopefully match md5sums with ROS.NET.

**Comment by gavanderhoorn** [comment]
Ah ok. My apologies.

Any reason `Int16.msg` is not directly supported?

**Comment by nuclearmistake** [comment]
Have you seen YAMLParse and SerializationHelper?

**Comment by gavanderhoorn** [comment]
I think I can say 'yes' to both, but I don't quite follow ..

**Comment by nuclearmistake** [comment]
They tend to be quirky...  But once custom nessages build and md5s match, message generation issues quickly become less apparent, so I don't get around to fixing them.

Shorts for example, weren't even tested that intensely.

**Comment by nuclearmistake** [comment]
https://github.com/uml-robotics/ROS.NET/blob/master/common_msgs/sensor_msgs/Joy.msg

If you format the int16 array in Tactile.msg like that, or like int8[] in CompressedImage, then the md5sum of Tactile.msg should match the unmodified Ubuntu version.
