### ISSUE TITLE
Life Cycle

### ISSUE THREAD

**Issue by rvlietstra** [uml-robotics/ROS.NET#19]
Hi guys.
Thanks for ros.net!

I'm struggling with managing the lifecycle of my application. Are we suppose to be able to call ROS.init() again after a ROS.shutdown() ? Unfortunately it breaks due to some of the objects that get nulled and not reinitialized at shutdown. I tried fixing it, I can now call ROS.init again which connects to the robot but at some point I stop getting data.

Is there some other mechanism for managing the lifecycle of my application ?

The other problem I have is that NodeHandle.subscribe seems to hang indefinitely when the robot is not on the network. Any suggestions ?

Thanks!

**Comment by nuclearmistake** [comment]
Ros.init is designed to be run once during the program life cycle. Is your robot also the master? It might work better if you move your master to a VM or another machine that is always accessible. I can investigate and improve the behavior of subscribe, but you might consider threading the initialization of all of your subscribers, and forcing a reinitialization if you haven't received a message on one of your subs for some amount of time.

**Comment by rvlietstra** [comment]
Hi.
My robot is the master, a windows wpf app is subscribing via ROS.NET to the robot. Either machine might not be on the network due to startup times or network or other hardware failures.

The reason I wanted to shutdown and reinit ROS.NET was so that when someone accidentally types in a robot name incorrectly they wouldn't have to shut down the application to fix the situation.

Ok, 
1. I'll make the robot name a .config setting instead of a runtime setting. 
2. I'll call ROS.init only once
3. I'll try thread my subscription calls and kill the thread when it takes too long. Hopefully thread.abort works there. 

Good to know reinitialization of a subscription is an option.

Thanks!

**Comment by rvlietstra** [comment]
Ok, this works as expected.
Thanks!

**Comment by nuclearmistake** [comment]
You can also use environment variables to set the master uri. Just don't
set it programmatically and it will use user environment variables before
system environment variables
