### ISSUE TITLE
Duplicate messages

### ISSUE THREAD

**Issue by rvlietstra** [uml-robotics/ROS.NET#20]
Hi.
I'm investigating a duplicate message issue. Ros core is running on the robot, sending pose messages, the message sequence numbers look good from rostopic echo /pose. 

When I subscribe from ros.net with a queue size of 1 nh.subscribe<Messages.geometry_msgs.PoseStamped>("/pose", 1, poseCallback) I get some drops in the message sequence number, which is understandable. 

When I subscribe with a queue size of 2 almost all messages are sent to poseCallback twice. When I subscribe with a queue size of 3, I sometimes get up to 3 duplicates, with 10 up to 10 etc.

It almost looks like the messages are being queued, but the wrong one is sent to poseCallback, maybe the first one is always sent and the last one always dequeued ?

I tried setting the SAFE conditional compilation symbol, but had the same results.

Can you please point me to where the issue could be?

Thanks!

**Comment by nuclearmistake** [comment]
What is the publish rate? Is it possible that you're dropping  Does it behave properly when u run rostopic echo _off_ of the robot? 

I could have caused this regression in 0204a740 ... Try to recreate with it reverted locally?

**Comment by rvlietstra** [comment]
Hi.
I checked from an off robot rostopic echo that the sequence numbers are fine. I checked the latest version as well as the one committed before the one you mentioned, both duplicate sequence numbers. I'm busy debugging. Thanks

**Comment by rvlietstra** [comment]
Ok.

I think I know whats going on, haven't tried fixing it yet. 

When a MessageDeserializer<> is created it gets passed an IRosMessage. The MessageDeserializer<> then gets cached. I think the MessageDeserializer<> should be passed the message to deserialize, but it never is. MessageDeserializer<> only has a method deserialize(), which deserializes the IRosMessage that was passed to the MessageDeserializer<> when it was created. 

The MessageDeserializer<> shouldnt store the IRosMessage in itself. 

Does that make sense ?

Thanks!

**Comment by nuclearmistake** [comment]
I'm testing with a rospy pose publisher publishing posestampeds with constantly incrementing seq (set manually) at 100hz with a queue size of 100.

In a ros.net node, I have a subscriber with a queue size I'm varying, and in its callback, I'm testing for conditions where the same seq occurs more than once, and a condition where the seq changes by more than 1 between subsequent callbacks.

It seems to only be occurring when the node is first starting up, or when I select text in the terminal (which blocks writing to it). It does seem to not be a problem when queue size is 1.

Your diagnosis is reasonable, but I'm inclined to think it's closer to the subscriber queue's behavior after a message is passed up to the callbacks, as the bug does not occur when the size is 1.

**Comment by nuclearmistake** [comment]
https://github.com/uml-robotics/ROS.NET/commit/e5f16a98337a15dde7d9fbfefaa9670f65a974e3 do the trick for you?

**Comment by rvlietstra** [comment]
Excellent thanks for the trouble!
