### ISSUE TITLE
Service call hangs when ROS master dies.

### ISSUE THREAD

**Issue by rvlietstra** [uml-robotics/ROS.NET#22]
Hi.
Thanks for all the help so far!

When the ROS master dies a service method hangs. 
The hang is in https://github.com/uml-robotics/ROS.NET/blob/master/ROS_Comm/ServiceServerLink.cs#L311

The mutex is never released because the call never finishes.

This particular service is called 10 times a second, so I'd like to not recreate it every time. Other services, who I recreate each time I call them, work after rosmaster is back up.

Do you think there should be a timeout somewhere ? Should I rather do the timeout in my own code ?

Thanks!

**Comment by nuclearmistake** [comment]
That is also the behavior with rospy and roscpp with a non-persistent service client. It also blocks indefinitely when the master dies, and service call timeouts are usually handled after the arguments are sent to the server. You could use Service.waitForService's return value to detect if the service exists with a specified timeout, and only call it if it does

**Comment by rvlietstra** [comment]
Ok thanks I'm handling the timeout myself with a thread join, which seems to work.
