### ISSUE TITLE
It is unclear if Subscription succeded

### ISSUE THREAD

**Issue by rvlietstra** [uml-robotics/ROS.NET#23]
Hi.
Master.execute() times out when a RPC call fails so NodeHandle.subscribe<M>() returns a subscriber even when TopicManager.Instance.subscribe(ops) fails. This means there is no way of knowing if a subscription was successful or not. I checked rospy and it seems registration of subscriptions never time out. I think NodeHandle.subscribe<M>() should either return null or subscriptions/master.execute should block. What do you think ?

Thanks!!

**Comment by nuclearmistake** [comment]
It could be made to retry indefinitely IMO.

I habitually thread ROS init in my ros.net applications, so it's likely to be problematic as far as the wpf image classes and dynreconf than possibly returning null from nh.subscribe, as non-null subscribers can be desubscribed manually.

I'll admit that ros.net's behavior without communication to a master is a bit undefined... But my only reservation about blocking subscription indefinitely is that new projects default to using the vs hosting process, and it or the wpf designer might cause VS to lock up, become unhappy, or crash if they try to initialize some of ROS without a present master.

It, however, wouldn't be a waste of time to investigate.

**Comment by rvlietstra** [comment]
What has worked for me in terms of the wpf designer is:
```C#
        public static bool IsInDesignMode()
        {
            if (System.Reflection.Assembly.GetExecutingAssembly().Location.Contains("VisualStudio"))
            {
                return true;
            }
            return false;
        }
```

I'v seen Subscrition<> has a node handle which I now check to see if the subscription was successful or not, so I'm retrying the subscriptions myself. 

The only other thing I'm struggling with is shutting down when there was no master, the process almost always hangs and hogs the .exe, sometimes I need to exit visual studio. The hang was introduced in the last update, it hang at: https://github.com/uml-robotics/ROS.NET/blob/master/ROS_Comm/XmlRpcManager.cs#L355, I'v removed the entire foreach without ill effect.

There are also instances where clients list in that block could be modified while iterating, eg. if you sequentially list out all your subscriptions like you would in rospy, then while exiting in the first (5 seconds x the number of subscriptions you have) seconds then there might be a subscription added to that list, so if you do want that cleaned up maybe do it some other way.

It seems the reason the XmlRpcManger cannot close down correctly is because there is a semaphore blocking https://github.com/uml-robotics/ROS.NET/blob/master/ROS_Comm/CallbackQueue.cs#L296 . I haven't investigated why.

Multi threading is super tricky.

My application is now mostly stable whether there is a ros master or not.

Thanks!

**Comment by nickkazepis** [comment]
So is there a suggested workflow to wait for the roscore to become available in order for the subscribers/publishers to succeed? @rvlietstra maybe you could provide some of your insights how did you manage to make your program stable with or without the master?

**Comment by nickkazepis** [comment]
For registering subscribers this seems to work:
```C#
_subscriber = _nodeHandle.subscribe<Messages.std_msgs.String>("/chatter", 10, SubCallback);
while (_subscriber.nodehandle == null)
{
    _subscriber = _nodeHandle.subscribe<Messages.std_msgs.String>("/chatter", 10, SubCallback);
}
```

However, then there is no `roscore` running, the ROS.Init complains that it failed to register the `/clock` topic.
Can this be somehow overcome? What is the `/clock` anyway?
@nuclearmistake should I create another issue to discuss this?

**Comment by nuclearmistake** [comment]
https://github.com/uml-robotics/ROS.NET/tree/waitForMaster

**Comment by nuclearmistake** [comment]
that's the shortest path for "waiting for rosmaster forever", but will block Main

/clock is used to modify the behavior of ROS.GetTime() to return time values extrapolated from the last simtime published, if simtime is being published

**Comment by nickkazepis** [comment]
@nuclearmistake you are the best! Thanx! I will use it inside a Task.Run to prevent it from blocking!

**Comment by nuclearmistake** [comment]
The master branch now has an opt-in equivalent to this hardcoded one... just call ROS.WaitForMaster() before calling ROS.Init
https://github.com/uml-robotics/ROS.NET/commit/47c3080d0dab022c22a2bac618066e342ab28b56

**Comment by nuclearmistake** [comment]
or https://github.com/uml-robotics/ROS.NET/commit/ac1cb299aff1eaa74301d7c53dfa915eacdc2d2b , rather

**Comment by nickkazepis** [comment]
Nice! Thanx a lot!
