### ISSUE TITLE
Release build

### ISSUE THREAD

**Issue by rvlietstra** [uml-robotics/ROS.NET#24]
Hi.
Just copying the release build XmlRpcWin32.dll over the debug build XmlRpcWin32.dll causes comms to fails silently. Is there a difference between release and debug ? Unfortunately the machine I am deploying to doesn't have the windows debug xxxxxD.dlls.

Could this simply be a build issue on my side ?

Thanks!!

**Comment by nuclearmistake** [comment]
Double-check the post-build and pre-build scripts, and that all of the projects are built in the release configuration. I haven't tried building release. Hehe

You might also try the next branch, which uses C# xmlrpc,  but has a weird issue with reading an http header that seems to only present with the ROS.net dynamic reconfigure gui :-/

**Comment by nuclearmistake** [comment]
The XmlRpcWin32 project could just need its libs changed in its properties for the release configuration

**Comment by rvlietstra** [comment]
Ok, I'm trying out the "next" branch.
Where is xmlrpc ? It seems there suppose to be a project for it, but its missing.
Have you not checked it in yet ? or am I doing something wrong ?
Thanks

**Comment by rvlietstra** [comment]
Ok, I downloaded xmlrpc and placed it in the correct place.
The issue I have now is "XmlRpc_Wrapper.TypeEnum" is not defined anywhere.

**Comment by nuclearmistake** [comment]
Maybe try the libs on master for xmlrpcwin32... The on the next branch there might be a few "XmlRpc" includes left over from the merge ... But those should be XmlRpc_Wrapper like on master. XmlRpc_Wrapper on next just no longer needs XmlRpcWin32.dll

**Comment by nuclearmistake** [comment]
https://github.com/uml-robotics/ROS.NET/commit/80efae601542bf4ed18cbcf1cd92934574e5fcf4

Make sure to turn off "vs hosting" under debug on your project... does nothing but break stuff in weird ways. O.o

**Comment by rvlietstra** [comment]
Unfortunately I'm still having silent issues on release build. I'v now checked with wireshark and it seems I'm simply not getting the packets I should be. Rostopic on the master master correctly says that the windows machine is subscribed to that topic. The topic in question's packet is large enough (2k) to spot in wireshark and with the xmlrpcwin32 built in debug I do see those packets, but not when I build in release. I'm stumped ... Is everything working fine when you build in release ? vs hosting is not ticked.

**Comment by gavanderhoorn** [comment]
@rvlietstra: maybe you already know this, but the recently released Wireshark 2 (download [here](https://www.wireshark.org/download.html)) has a dissector for TCPROS ([release notes - new protocol support](https://www.wireshark.org/docs/relnotes/wireshark-2.0.0.html#_new_protocol_support)). Might help debugging.

**Comment by rvlietstra** [comment]
Oh, nice I haven't seen that, thanks.
I'v now checked and rechecked and it seems the moment I build the c++ lib with /MD instead of /MDd I get this issue. I'v turned off all optimization, I'v event tried changing the debug config to /MD and still get the issue. I believe it might be a race condition / deadlock somewhere ... but let me check again with TCPROS.
Thanks

**Comment by rvlietstra** [comment]
Ok I know where the issue is. 
https://github.com/uml-robotics/ROS.NET/blob/master/ROS_Comm/Subscription.cs#L260
IsConnected on that line when building xmlrpcwin32 with a non debug build is _almost_ alway false. I tried figuring out why, but for now I'v just removed the IsConnected check and it seems to work.
Thanks

**Comment by rvlietstra** [comment]
Ok, 
I'm now using the c# xmlrpc_wrapper version and that seems a lot more stable.
Thanks
