### ISSUE TITLE
How to handle roscore failures

### ISSUE THREAD

**Issue by foukas** [uml-robotics/ROS.NET#36]
Hi there, I have a ROS.NET client in Windows communicating with roscore on Ubuntu Linux. Publishers/subscribers seem to communicate just fine, but when roscore is restarted nothing is working anymore. I believe that the client is not aware of this and is somehow tied to the "old" roscore which was shut down. There is no error message.

Is there a way to notify my client about the roscore status and maybe re-create the topics if necessary? The topics are originally created by my node.

Thank you very much for your work!

**Comment by nuclearmistake** [comment]
If you're using roslaunch to start roscore, I'd recommend starting a roscore before you roslaunch so that it persists between re-launches of the backend... short of that, you could
`//with NodeHandle "nh" and all pubs+subs stored in class scope
var ROSRestarter = new Thread(()=>{
while (!shouldStopRepeatedlyStartingROS) {
ROS.WaitForMaster();
ROS.Init(...);
nh = new NodeHandle();`
// init all pubs+subs and stuff
while (!shouldStopRepeatedlyStartingROS && master.check())
{
Thread.Sleep(500);
}
ROS.Shutdown();
ROS.WaitForShutdown();
}
}){IsBackground=true};
ROSRestarter.Start();`

BUT I can't guarantee that all of the singleton *Manager classes will tolerate repeated shutdowns+inits on different masters. The "make roscore be more persistent" option is your best bet IMO

**Comment by foukas** [comment]
Thanks for the advice and sample code. For the time being I'm just launching the master with a roscore command from the terminal.
I'm testing cases where the master has crashed or needs to be restarted (e.g. with Ctrl-C and roscore) or the network connection fails. I guess in this case, I have to use something like the snippet you posted. However, I'm not sure what the master.check() method should actually do. Is there a way to check for connection with the master with ROS.NET or pure C#?
I apologize if the question is beyond the scope of ROS.NET.

**Comment by foukas** [comment]
D'oh, I just realized that master.check() is an existing static method (I thought I had to implement it). In this case, if roscore terminates and is restarted while in Thread.Sleep(500), master.check() will still return true for the latest master, but the existing pubs/subs will be invalid. This can be solved with a shorter duration for Sleep but I'm not sure if it's the best idea.

**Comment by nuclearmistake** [comment]
could probably check at 10 or even 100 Hz without any issue... but making roscore invincible is your best bet... all ros clients are similarly intolerant to roscore suddenly dying

**Comment by foukas** [comment]
I tried your code and there is an issue. You can recreate it quickly using this sequence, which shuts down and restarts the client and the nodehandle:
```
ROS.WaitForMaster();
ROS.Init(...);
nh = new NodeHandle();
ROS.shutdown();
ROS.waitForShutdown();

ROS.WaitForMaster();
ROS.Init(...);
nh = new NodeHandle();
```
Roscore was running without interruption while executing this code. The exception happens in XmlRpcServer.cs inside AddMethod: "An item with the same key has already been added"

**Comment by nuclearmistake** [comment]
YUP... 

> I can't guarantee that all of the singleton *Manager classes will tolerate repeated shutdowns+inits on different masters

ROS.Init was never intended to happen twice... so there might be all kinds of unforeseen garbage left all sorts of places from the first ROS.Init that isn't removed by the ROS.shutdown()

**Comment by foukas** [comment]
I see... So if roscore dies, there is no way to reestablish the connection? Ideally in production this should never happen, but from my experience it occurs sometimes while developing robot software and the system is unstable.

**Comment by nuclearmistake** [comment]
It does sometimes happen... but the behavior is the same for roscpp and rospy... any existing topics remain, but the replacement master is unaware that the nodes exist.

**Comment by foukas** [comment]
OK, then I guess there is no straightforward way to handle this. Thanks for the help!
