### ISSUE TITLE
Multi ROS

### ISSUE THREAD

**Issue by baeckermeister** [uml-robotics/ROS.NET#38]
Hi, I would like to use multiple instances of the singleton ROS-Class. I tried to figure out, how all the things stick together, but it seems that this is hard to change ? I started to remove all the static object and added references to one particular ROS-Object, but gave up, because I lost the overview.

Background: I try to make one programm let me control multiple robots. At this time the only thing I can do is, run multiple programms. 

Any Ideas ?

**Comment by nuclearmistake** [comment]
Why not have them all use the same master? It can be achieved with namespacing and tf_prefixes.

**Comment by baeckermeister** [comment]
thank you! never thought about that.should be possible / less work, just a few remappings.thx
