### ISSUE TITLE
ROS.NET actively maintained?

### ISSUE THREAD

**Issue by bkinman** [uml-robotics/ROS.NET#39]
Is anybody actively maintaining this?
I see that Xamla has forked it, and has continued to develop on it.
Does it make more sense to use that fork?

**Comment by stgusr** [comment]
I created a fork, but have not been able to work on it.

**Comment by allspawj** [comment]
The old developer nuclearmistake has moved on and is no longer maintaining ROS.NET.
I am actively using ROS.NET and it works for my needs, I may take some time to make improvements this summer but at the moment it works for me without issue.

Looks like Xamla is doing some development on it, if his stuff seems useful to you then feel free to use his fork.
