### ISSUE TITLE
set ROS_HOSTNAME and ROS_MASTER_URI

### ISSUE THREAD

**Issue by foerbsn** [uml-robotics/ROS.NET#40]
What do I have to set for those variables?
Is there a roscore included in this package, or can/must I use a remote roscore?
My plan is to write a node using ros.net, but communicate with nodes and the roscore running on ubuntu. I set ROS_HOSTNAME to <ubuntu_pc_name> and ROS_MASTER_URI to "http://<ip>:11311/" (copy and paste from running roscore in console), but when I compile and run ROS_dotNET_ROS_SAMPLES in visual studio, all I get is a window "call failed after x ms"

**Comment by gavanderhoorn** [comment]
>  I set `ROS_HOSTNAME` to <ubuntu_pc_name>

`ROS_HOSTNAME` is never set to the name of another machine, *always* to the name of the machine running the node.

But unless you have working DNS for *all* involved hosts, using `ROS_IP` is probably going to be easier.

> and ROS_MASTER_URI to `http://<ip>:11311/`

If that `<ip>` is the IP of the ubuntu machine running the master, that should work.

**Comment by foerbsn** [comment]
So what is ROS_IP now? ^^
So there is also included a roscore in ros.net?
What do I set the ip to if i want to run the package only by itself? http://127.0.0.1:11311/ ?
Or is it a IP i can choose freely and the roscore is then running using that ip?

**Comment by nuclearmistake** [comment]
Set them in windows environment variables, OR they can be set
programmatically via statics on the ROS class (less portable).

A remote rosmaster running on a Linux machine is preferable. If you are
using roslaunch for nodes on your robot or Ubuntu ROS nodes, start
"roscore" backgrounded or in a separate shell, so that you can restart
roslaunch OR your ros.net node without rosmaster disappearing during the
lifespan of either your windows or Linux nodes.

**Comment by gavanderhoorn** [comment]
Note: I'm not a developer nor maintainer of this pkg.

> So what is ROS_IP now? ^^

`ROS_IP`, `ROS_HOSTNAME`, `ROS_MASTER_URI` are basic ROS networking env vars. I'd refer you to [ros/wiki/ROS/EnvironmentVariables - Node Environment Variables](http://wiki.ros.org/ROS/EnvironmentVariables#Node_Environment_Variables) and [ros/wiki/ROS/NetworkSetup](http://wiki.ros.org/ROS/NetworkSetup).

> So there is also included a roscore in ros.net?

I don't know.

> What do I set the ip to if i want to run the package only by itself? http://127.0.0.1:11311/ ?
> Or is it a IP i can choose freely and the roscore is then running using that ip?

no, you cannot just make something up. But the two linked wiki pages should make that clear.

**Comment by nuclearmistake** [comment]
Example:
Ubuntu (IP:192.168.1.10)
  export ROS_HOSTNAME="192.168.1.10"
  export ROS_MASTER_URI="http://192.168.1.10:11311"
  roscore &
  # wait for master to start
  roslaunch somepackage something.launch

Windows (192.168.1.11)
  # Set in windows environment variables
  ROS_HOSTNAME=192.168.1.11
  ROS_MASTER_URI=http://192.168.1.10:11311

  # run ros.net program

**Comment by foerbsn** [comment]
Great, it worked. I could run the Talker and display the messages using rostopic echo. Thanks a lot.
