### ISSUE TITLE
Help need: Message Reference Missing

### ISSUE THREAD

**Issue by wmqazi** [uml-robotics/ROS.NET#41]
I download the code for ROS.NET and compiled using visual studio 2015. I getting compilation error with reference to Message Reference Missing and I am unable to find one in the code.

Kindly help/guide

**Comment by nuclearmistake** [comment]
Which .sln did you open?

**Comment by wmqazi** [comment]
I had tried all .sln, but finally, it worked. I have added a message project and installed.NET Framework 3.5. in previous attempts, I upgraded to the project to 4.5 with VS studio 2015.

Thanks
