### ISSUE TITLE
Unable to publish a GoalId without stamp.

### ISSUE THREAD

**Issue by BascoDLowell** [uml-robotics/ROS.NET#52]
I am trying to cancel all goals by sending a `GoalId` message with empty `id` and `stamp`, as was mentioned at [ROS wiki](http://wiki.ros.org/actionlib/DetailedDescription#The_Messages). 
![roswiki](https://user-images.githubusercontent.com/14083887/53611835-dad14c80-3c0a-11e9-8efa-e8a3267b1d88.PNG)

So far I tried publishing goal like:
```
Messages.actionlib_msgs.GoalID goal = new Messages.actionlib_msgs.GoalID
            {
                id = "",
                stamp = null
            };
```
But it would throw an exception as:

> Info: System.NullReferenceException at Messages.actionlib_msgs.GoalID.Serialize(Boolean) at Messages.IRosMessage.Serialize() at Ros_CSharp.TransportSubscriberLink.startMessageWrite(Boolean) at Ros_CSharp.TransportSubscriberLink.enqueueMessage(Ros_CSharp.MessageAndSerializerFunc) at Ros_CSharp.Publication.EnqueueMessage(Ros_CSharp.MessageAndSerializerFunc) at Ros_CSharp.Publication.processPublishQueue() at Ros_CSharp.Poll_Signal.threadFunc() at System.Threading.ThreadHelper.ThreadStart_Context(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.ThreadHelper.ThreadStart()

I'm quite sure, the problem is with the `stamp` as I was able to publish successfully with same empty `id` and a filled-up `stamp`.

**Comment by nuclearmistake** [comment]
Have you tried setting the stamp to 0,0?

**Comment by BascoDLowell** [comment]
I'll try and get back to this.

**Comment by nuclearmistake** [comment]
Thanks

**Comment by BascoDLowell** [comment]
Hi @nuclearmistake ! My publisher is on one computer while my subscriber/Ros master is on another computer. I specifically need to get the .now of the Ros master. 
May I know how could I do it?
I saw you have a function `Ros_CSharp.ROS.GetTime()` without argument. May I know what this is doing?

**Comment by nuclearmistake** [comment]
GetTime() should be synced to either wall time or Ros time if it's available... If I recall

**Comment by nuclearmistake** [comment]
/// <summary>
        ///     Gets the current time as secs/nsecs
        /// </summary>
        /// <returns> </returns>
        public static m.Time GetTime()
        {
            return GetTime(DateTime.Now);
        }

It's in ROS_Comm/_init.cs

**Comment by nuclearmistake** [comment]
Usually NTP and windows network time are advised, as Ros /time is usually more of bag / stage / gazebo thing

**Comment by BascoDLowell** [comment]
hmm, I see. So I really just have to find a way to set stamp to null. Is it possible with this library?

**Comment by nuclearmistake** [comment]
You could publish a goalid from a regular Ros not with a "null" stamp, and watch what is actually sent in rostopic echo... Then *emulate* that behavior manually in ros.net.

I guarantee transmitting a null stamp on rospy or roscpp does actually send something... Make your ros.net code sent *that*

That should behave like you want, although you're not literally using a null stamp

**Comment by BascoDLowell** [comment]
Ok, will try that. Thanks for the help!

**Comment by nuclearmistake** [comment]
You're welcome

**Comment by BascoDLowell** [comment]
This solves the issue:
```
Messages.actionlib_msgs.GoalID goal = new Messages.actionlib_msgs.GoalID
            {
                id = "",
                stamp = new Messages.std_msgs.Time
                        ( 
                            new Messages.TimeData
                            {
                                sec = 0,
                                nsec = 0
                            }
                        )

            };
```

Thanks @nuclearmistake ! You may now close this issue!

**Comment by nuclearmistake** [comment]
Glad to hear that you got it working.
